# Cloudflare Pages configuration
name = "rite-sveltekit-poc"
compatibility_date = "2025-01-27"
compatibility_flags = ["nodejs_compat"]

# Environment variables for Cloudflare Pages
[vars]
VITE_CONVEX_URL = "https://valiant-curlew-94.convex.cloud"
INSTAGRAM_OAUTH_PROXY_URL = "https://rite-instagram-oauth-proxy.sehyunchung.workers.dev"
NODE_ENV = "production"