name = "rite-sveltekit-poc"
main = ".svelte-kit/cloudflare/_worker.js"
assets = { directory = ".svelte-kit/cloudflare", binding = "ASSETS" }
compatibility_date = "2025-01-27"

# Workers Paid plan is required for always warm
workers_dev = true
compatibility_flags = ["nodejs_compat"]

# Modern Workers deployment - no [site] needed for SvelteKit

# Environment variables
[vars]
VITE_CONVEX_URL = "https://valiant-curlew-94.convex.cloud"
NEXTAUTH_URL = "https://rite-sveltekit-poc.sehyunchung.workers.dev"
INSTAGRAM_OAUTH_PROXY_URL = "https://rite-instagram-oauth-proxy.sehyunchung.workers.dev"
NODE_ENV = "production"

# Bindings
# [env.production.vars]
# SOME_VAR = "production_value"

# Routes configuration (commented out for Workers subdomain deployment)
# [[routes]]
# pattern = "/*"
# zone_name = "rite.party" # Replace with your domain when ready

# Build configuration
[build]
command = "pnpm run build"

# Development configuration
[dev]
port = 8788
local_protocol = "http"

# Observability (logging)
[observability.logs]
enabled = true