# Cloudflare Workers configuration
name = "rite-sveltekit"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-01-27"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Workers Versions configuration
[versions]
compatibility_date = "2025-01-27"
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
command = "pnpm run build"
cwd = "apps/sveltekit-poc"
watch_paths = ["src/**/*.{js,jsx,ts,tsx,svelte}"]

# Environment variables
[vars]
VITE_CONVEX_URL = "https://valiant-curlew-94.convex.cloud"
INSTAGRAM_OAUTH_PROXY_URL = "https://rite-instagram-oauth-proxy.sehyunchung.workers.dev"
NODE_ENV = "production"