name = "rite-instagram-oauth-proxy"
main = "src/index.ts"
compatibility_date = "2024-07-20"

[observability.logs]
enabled = true

[env.development]
name = "rite-instagram-oauth-proxy-dev"

[env.production]
name = "rite-instagram-oauth-proxy"

# Environment variables (set via `wrangler secret put`)
# INSTAGRAM_CLIENT_ID
# INSTAGRAM_CLIENT_SECRET
# RITE_APP_URL