/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DjSubmissionRouteImport } from './routes/dj-submission'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsCreateRouteImport } from './routes/events/create'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AuthInstagramSuccessRouteImport } from './routes/auth/instagram/success'
import { Route as AuthInstagramCallbackRouteImport } from './routes/auth/instagram/callback'

const AdminRouteImport = createFileRoute('/admin')()

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DjSubmissionRoute = DjSubmissionRouteImport.update({
  id: '/dj-submission',
  path: '/dj-submission',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const AuthInstagramSuccessRoute = AuthInstagramSuccessRouteImport.update({
  id: '/auth/instagram/success',
  path: '/auth/instagram/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInstagramCallbackRoute = AuthInstagramCallbackRouteImport.update({
  id: '/auth/instagram/callback',
  path: '/auth/instagram/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dj-submission': typeof DjSubmissionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/create': typeof EventsCreateRoute
  '/events': typeof EventsIndexRoute
  '/auth/instagram/callback': typeof AuthInstagramCallbackRoute
  '/auth/instagram/success': typeof AuthInstagramSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dj-submission': typeof DjSubmissionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/create': typeof EventsCreateRoute
  '/events': typeof EventsIndexRoute
  '/auth/instagram/callback': typeof AuthInstagramCallbackRoute
  '/auth/instagram/success': typeof AuthInstagramSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dj-submission': typeof DjSubmissionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/create': typeof EventsCreateRoute
  '/events/': typeof EventsIndexRoute
  '/auth/instagram/callback': typeof AuthInstagramCallbackRoute
  '/auth/instagram/success': typeof AuthInstagramSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dj-submission'
    | '/login'
    | '/privacy'
    | '/admin'
    | '/admin/dashboard'
    | '/events/$eventId'
    | '/events/create'
    | '/events'
    | '/auth/instagram/callback'
    | '/auth/instagram/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dj-submission'
    | '/login'
    | '/privacy'
    | '/admin'
    | '/admin/dashboard'
    | '/events/$eventId'
    | '/events/create'
    | '/events'
    | '/auth/instagram/callback'
    | '/auth/instagram/success'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dj-submission'
    | '/login'
    | '/privacy'
    | '/admin'
    | '/admin/_layout'
    | '/admin/dashboard'
    | '/events/$eventId'
    | '/events/create'
    | '/events/'
    | '/auth/instagram/callback'
    | '/auth/instagram/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DjSubmissionRoute: typeof DjSubmissionRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  AdminRoute: typeof AdminRouteWithChildren
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsCreateRoute: typeof EventsCreateRoute
  EventsIndexRoute: typeof EventsIndexRoute
  AuthInstagramCallbackRoute: typeof AuthInstagramCallbackRoute
  AuthInstagramSuccessRoute: typeof AuthInstagramSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dj-submission': {
      id: '/dj-submission'
      path: '/dj-submission'
      fullPath: '/dj-submission'
      preLoaderRoute: typeof DjSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/create': {
      id: '/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/instagram/success': {
      id: '/auth/instagram/success'
      path: '/auth/instagram/success'
      fullPath: '/auth/instagram/success'
      preLoaderRoute: typeof AuthInstagramSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/instagram/callback': {
      id: '/auth/instagram/callback'
      path: '/auth/instagram/callback'
      fullPath: '/auth/instagram/callback'
      preLoaderRoute: typeof AuthInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRoute,
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DjSubmissionRoute: DjSubmissionRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  AdminRoute: AdminRouteWithChildren,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsCreateRoute: EventsCreateRoute,
  EventsIndexRoute: EventsIndexRoute,
  AuthInstagramCallbackRoute: AuthInstagramCallbackRoute,
  AuthInstagramSuccessRoute: AuthInstagramSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
